services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: React
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/disclone/frontend
      - /disclone/frontend/node_modules
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               daphne disclone_proj.asgi:application --bind 0.0.0.0:8000 &&
               gunicorn dislone_proj.wsgi:application --bind 0.0.0.0:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/disclone/backend
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    command: celery -A disclone_proj worker --loglevel=info
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


volumes:
  postgres_data: