services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: React
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/disclone/frontend
      - /disclone/frontend/node_modules
    depends_on:
      - gunicorn
      - daphne
  
  gunicorn:
    build:
      context: ./backend
      dockerfile: Dockerfile.gunicorn
    container_name: django_gunicorn
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db
      - DEBUG=True
    ports:
      - '8001:8001'
    depends_on:
      - db
      - redis

  daphne:
    build:
      context: ./backend
      dockerfile: Dockerfile.daphne
    container_name: django_daphne
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db
      - DEBUG=True
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


volumes:
  postgres_data: