version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db

    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - '5173:5173'
    
    volumes:
      - ./frontend:/disclone/frontend
      - /disclone/frontend/node_modules

    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disclone_db
    
    ports:
      - '8000:8000'
    
    volumes:
      - ./backend:/disclone/backend
    
    depends_on:
      - db

volumes:
  postgres_data: