FROM python:3.12.3-slim-bullseye

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /disclone/backend

COPY requirements.txt /disclone/backend/
RUN pip install -r requirements.txt

COPY . /disclone/backend/

CMD ["gunicorn", "disclone_proj.wsgi:application", "--bind", "0.0.0.0:8001", "--workers", "4"]